### PR TITLE
fix: merge appState in Auth Guard

### LINKED ISSUE #434: Merge AuthGuardOptions.redirectLoginOptions.appState in AuthGuard
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We have a lot of SPAs so we are using a central "/login-redirect" callback path for all logins; as suggested by the Auth0 docs we are storing the actual return path in `appState`, and the callback reads the appState value and generates the proper redirect.

Our problem is that our SPAs run under subpaths, so the `appState.target` value isn't sufficient for a full redirect as it only stores the relative routing path within the SPA.

We addressed this by including the base path in the appState:

```
const authGuard = createAuthGuard({
  redirectLoginOptions: { appState: { basePath: process.env.PUBLIC_PATH } },
});
```

With this, we get the base path back but we've lost the target (routing) path, because the guard code overwrites the `appState` entirely if one is provided in redirectLoginOptions, see https://github.com/auth0/auth0-vue/blob/main/src/guard.ts#L20:

```
    await client.loginWithRedirect({
      appState: { target: to.fullPath },
      ...redirectLoginOptions
    });
```

It would be helpful if this code merged the `appState` values here, so the resulting state has both the provided values and the calculated target value, ie.

```
    await client.loginWithRedirect({
      appState: { 
        ...redirectLoginOptions.appState,
        target: to.fullPath,
      },
      ...redirectLoginOptions
    });
```

### Describe the ideal solution

If `RedirectLoginOptions.appState` is passed into the authGuard, the resulting appState includes both this and the `target` path added by the authGuard.

### Alternatives and current workarounds

Our current workaround does the target mapping explicitly:

```
async function authGuard(to: RouteLocation) {
  return createAuthGuard({
    redirectLoginOptions: {
      appState: {
        target: to.fullPath,
        basePath: process.env.PUBLIC_PATH,
      },
    },
  })(to);
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by frederikprijck**
### Changes

When a user would provide `appState` on `redirectLoginOptions` when creating the Auth Guard, we would lose any `appState.target` value, due to the fact that this was not being accounted for.

### References

Closes #434 

### Testing

- [x] This change adds unit test coverage
- [ ] This change adds integration test coverage
- [x] This change has been tested on the latest version of the platform/language

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines have been run/followed

### CODE REVIEW

**Review by yogeshchoudhary147 — DISMISSED** [review]

File: src/guard.ts [hunk 1]
```diff
@@ -18,8 +18,11 @@ async function createGuardHandler(
     }
 
     await client.loginWithRedirect({
-      appState: { target: to.fullPath },
-      ...redirectLoginOptions
+      ...redirectLoginOptions,
+      appState: {
+        target: to.fullPath,
+        ...redirectLoginOptions?.appState
```
Comment (yogeshchoudhary147) [inline src/guard.ts:24]: shouldn't `target` come last here? it changes on every navigation so it should always override the static value set at startup

File: src/guard.ts [hunk 2]
```diff
@@ -44,7 +47,9 @@ export interface AuthGuardOptions {
   app?: App;
 
   /**
-   * Route specific options to use when being redirected to Auth0
+   * Route specific options to use when being redirected to Auth0.
+   * If appState is provided, it will be merged with the guard's automatic
+   * target property. The guard's target always takes precedence.
```
Comment (yogeshchoudhary147) [inline src/guard.ts]: the guard's target is `to.fullPath` but developer's appState can override it so this comment seems wrong?

Comment (frederikprijck) [inline src/guard.ts]:
```suggestion
   * target property. Any target provided in appState will take precedence over the guard's default target.
```

**Review by yogeshchoudhary147 — APPROVED** [review]
